CREATE DATABASE LOGIN;
USE LOGIN;

CREATE TABLE Users(
    USER_ID INT     AUTO_INCREMENT,
    USERNAME        VARCHAR(40),
    PASSWORD        VARCHAR(255),
    EMAIL           VARCHAR(255),
    CONSTRAINT PK_Users PRIMARY KEY (USER_ID)
);

CREATE TABLE Roles(
    ROLE_ID INT     AUTO_INCREMENT,
    ROLE_NAME       VARCHAR(50),
    CONSTRAINT PK_Roles PRIMARY KEY (ROLE_ID)
);

CREATE TABLE Middle(
    USER_ID         INT NOT NULL ,
    ROLE_ID         INT NOT NULL ,
    CONSTRAINT FK_Users_Middle FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID),
    CONSTRAINT FK_Roles_Middle FOREIGN KEY (ROLE_ID) references Roles(ROLE_ID)
);
