CREATE DATABASE My_Data;
USE My_Data;

CREATE TABLE Contacts(
    CONSTACT_ID INT(11) AUTO_INCREMENT,
    CONSTRAINT PK_Contacts PRIMARY KEY (CONSTACT_ID),
    LAST_NAME VARCHAR(50) NOT NULL ,
    FIRST_NAME VARCHAR(50),
    BIRTHDAY DATE
);

CREATE TABLE Supplier(
    SUPPLIER_ID INT(11) AUTO_INCREMENT,
    CONSTRAINT  PK_Supplier PRIMARY KEY (SUPPLIER_ID),
    SUPPLIER_NAME VARCHAR(50) NOT NULL ,
    ACCOUNT_REP VARCHAR(30) NOT NULL DEFAULT 'TBD'
);

SELECT * FROM My_Data.Contacts;

-- DROP 2 TABLE
DROP TABLE Contacts,Supplier;

-- ALTER ADD FIELD IN TABLE
ALTER TABLE My_Data.Contacts ADD ADDRESS VARCHAR(50) NOT NULL AFTER CONSTACT_ID;

-- ALTER ADD MANY FIELD IN TABLE

ALTER TABLE Contacts ADD CON_TYPE varchar(40) NOT NULL,
       -- AFTER CONSTACT_ID,
    ADD GENDER varchar(35) NULL;
       -- AFTER LAST_NAME;

--  MODIFY

ALTER TABLE My_Data.Contacts MODIFY FIRST_NAME VARCHAR(50) NOT NULL;

-- DROP COLUMN

ALTER TABLE My_Data.Contacts DROP COLUMN CON_TYPE;

-- CHANGE COLUMN

ALTER TABLE My_Data.Contacts CHANGE COLUMN GENDER SEX BIT DEFAULT 0;
-- CHANGE TABLE

ALTER TABLE My_Data.Contacts RENAME TO People;
